apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: example-operators
  namespace: openshift-marketplace
spec:
  displayName: Example Operators
  image: 'registry.redhat.io/redhat/community-operator-index:v4.11'
  publisher: Acme Inc.
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
