apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-best-practices
placementBindingDefaults:
  name: binding-policy-openshift-best-practices
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  policySets:
    - openshift-best-practices
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
#- name: policy-limitclusteradmin # iam policy not supported by the generator
#  manifests:
#    - path: input-admin/policy-limitclusteradmin.yaml
- name: policy-remove-kubeadmin
  categories:
    - SC System and Communications Protection
  complianceType: "mustnothave"
  controls: 
    - SC-1 Policy and Procedures
  manifests:
    - path: input-admin/policy-remove-kubeadmin.yaml
  remediationAction: "inform"
policySets:
  - description: Applies the OpenShift best practices for how to harden your OpenShift clusters.
    name: openshift-best-practices
    placement:
      placementPath: input/placement.yaml
