apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
spec:
  customization:
    customLogoFile:
      key: custom-logo.jpg
      name: custom-logo
    customProductName: Console
  managementState: Managed
    
