apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- consoleNotification.yaml
- custom-logo-cm.yaml
- custom-logo-console.yaml
- project-config.yaml
- default-project-template.yaml
- input-mirror-configuration/icsp-example.yaml
- input-mirror-configuration/catalogsource-example.yaml
