apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patches:
- path: consoleNotification.yaml
- path: default-project-template.yaml
- path: input-mirror-configuration/icsp-example.yaml

